# Generated by Django 4.2.7 on 2023-11-06 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Парень'), ('female', 'Девушка')], default='', max_length=10)),
                ('age', models.DateField(default=datetime.date(2000, 11, 11))),
                ('telegram', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=20)),
                ('description', models.TextField(default='', max_length=1000)),
            ],
        ),
    ]
