# Generated by Django 4.2.7 on 2023-11-15 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='age',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='item',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='item',
            name='descr',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('Парень', 'Парень'), ('Девушка', 'Девушка')], default='other', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='item',
            name='tg',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
