# Generated by Django 3.2.12 on 2023-11-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregist',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
