# Generated by Django 4.2.7 on 2023-11-15 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_item_age_item_avatar_item_descr_item_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated_at',
        ),
    ]
