# Generated by Django 3.2.12 on 2023-11-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_userregist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregist',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
